/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0 */

#ifndef PB_MISC_TRONAPP_PB_H_INCLUDED
#define PB_MISC_TRONAPP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(72) ExchangeDetails_signature_t;
typedef struct _ExchangeDetails {
    uint64_t exchangeId;
    char token1Id[8];
    char token1Name[32];
    uint32_t token1Precision;
    char token2Id[8];
    char token2Name[32];
    uint32_t token2Precision;
    ExchangeDetails_signature_t signature;
} ExchangeDetails;


/* Initializer values for message structs */
#define ExchangeDetails_init_default             {0, "", "", 0, "", "", 0, {0, {0}}}
#define ExchangeDetails_init_zero                {0, "", "", 0, "", "", 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define ExchangeDetails_exchangeId_tag           1
#define ExchangeDetails_token1Id_tag             2
#define ExchangeDetails_token1Name_tag           3
#define ExchangeDetails_token1Precision_tag      4
#define ExchangeDetails_token2Id_tag             5
#define ExchangeDetails_token2Name_tag           6
#define ExchangeDetails_token2Precision_tag      7
#define ExchangeDetails_signature_tag            8

/* Struct field encoding specification for nanopb */
#define ExchangeDetails_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   exchangeId,        1) \
X(a, STATIC,   SINGULAR, STRING,   token1Id,          2) \
X(a, STATIC,   SINGULAR, STRING,   token1Name,        3) \
X(a, STATIC,   SINGULAR, UINT32,   token1Precision,   4) \
X(a, STATIC,   SINGULAR, STRING,   token2Id,          5) \
X(a, STATIC,   SINGULAR, STRING,   token2Name,        6) \
X(a, STATIC,   SINGULAR, UINT32,   token2Precision,   7) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         8)
#define ExchangeDetails_CALLBACK NULL
#define ExchangeDetails_DEFAULT NULL

extern const pb_msgdesc_t ExchangeDetails_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ExchangeDetails_fields &ExchangeDetails_msg

/* Maximum encoded size of messages (where known) */
#define ExchangeDetails_size                     181

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
