/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "core/Contract.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_AccountCreateContract, protocol_AccountCreateContract, AUTO)


PB_BIND(protocol_AccountUpdateContract, protocol_AccountUpdateContract, AUTO)


PB_BIND(protocol_TransferContract, protocol_TransferContract, AUTO)


PB_BIND(protocol_TransferAssetContract, protocol_TransferAssetContract, AUTO)


PB_BIND(protocol_VoteAssetContract, protocol_VoteAssetContract, AUTO)


PB_BIND(protocol_VoteWitnessContract, protocol_VoteWitnessContract, AUTO)


PB_BIND(protocol_VoteWitnessContract_Vote, protocol_VoteWitnessContract_Vote, AUTO)


PB_BIND(protocol_WitnessCreateContract, protocol_WitnessCreateContract, AUTO)


PB_BIND(protocol_WitnessUpdateContract, protocol_WitnessUpdateContract, AUTO)


PB_BIND(protocol_AssetIssueContract, protocol_AssetIssueContract, AUTO)


PB_BIND(protocol_AssetIssueContract_FrozenSupply, protocol_AssetIssueContract_FrozenSupply, AUTO)


PB_BIND(protocol_ParticipateAssetIssueContract, protocol_ParticipateAssetIssueContract, AUTO)


PB_BIND(protocol_DeployContract, protocol_DeployContract, AUTO)


PB_BIND(protocol_FreezeBalanceContract, protocol_FreezeBalanceContract, AUTO)


PB_BIND(protocol_UnfreezeBalanceContract, protocol_UnfreezeBalanceContract, AUTO)


PB_BIND(protocol_UnfreezeAssetContract, protocol_UnfreezeAssetContract, AUTO)


PB_BIND(protocol_WithdrawBalanceContract, protocol_WithdrawBalanceContract, AUTO)


PB_BIND(protocol_UpdateAssetContract, protocol_UpdateAssetContract, AUTO)


PB_BIND(protocol_ProposalCreateContract, protocol_ProposalCreateContract, AUTO)


PB_BIND(protocol_ProposalCreateContract_ParametersEntry, protocol_ProposalCreateContract_ParametersEntry, AUTO)


PB_BIND(protocol_ProposalApproveContract, protocol_ProposalApproveContract, AUTO)


PB_BIND(protocol_ProposalDeleteContract, protocol_ProposalDeleteContract, AUTO)


PB_BIND(protocol_TriggerSmartContract, protocol_TriggerSmartContract, AUTO)


PB_BIND(protocol_ExchangeCreateContract, protocol_ExchangeCreateContract, AUTO)


PB_BIND(protocol_ExchangeInjectContract, protocol_ExchangeInjectContract, AUTO)


PB_BIND(protocol_ExchangeWithdrawContract, protocol_ExchangeWithdrawContract, AUTO)


PB_BIND(protocol_ExchangeTransactionContract, protocol_ExchangeTransactionContract, AUTO)


PB_BIND(protocol_AccountPermissionUpdateContract, protocol_AccountPermissionUpdateContract, AUTO)




