/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PROTOCOL_CORE_TRON_PB_H_INCLUDED
#define PB_PROTOCOL_CORE_TRON_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/any.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _protocol_AccountType { 
    protocol_AccountType_Normal = 0, 
    protocol_AccountType_AssetIssue = 1, 
    protocol_AccountType_Contract = 2 
} protocol_AccountType;

typedef enum _protocol_Transaction_Contract_ContractType { 
    protocol_Transaction_Contract_ContractType_AccountCreateContract = 0, 
    protocol_Transaction_Contract_ContractType_TransferContract = 1, 
    protocol_Transaction_Contract_ContractType_TransferAssetContract = 2, 
    protocol_Transaction_Contract_ContractType_VoteAssetContract = 3, 
    protocol_Transaction_Contract_ContractType_VoteWitnessContract = 4, 
    protocol_Transaction_Contract_ContractType_WitnessCreateContract = 5, 
    protocol_Transaction_Contract_ContractType_AssetIssueContract = 6, 
    protocol_Transaction_Contract_ContractType_WitnessUpdateContract = 8, 
    protocol_Transaction_Contract_ContractType_ParticipateAssetIssueContract = 9, 
    protocol_Transaction_Contract_ContractType_AccountUpdateContract = 10, 
    protocol_Transaction_Contract_ContractType_FreezeBalanceContract = 11, 
    protocol_Transaction_Contract_ContractType_UnfreezeBalanceContract = 12, 
    protocol_Transaction_Contract_ContractType_WithdrawBalanceContract = 13, 
    protocol_Transaction_Contract_ContractType_UnfreezeAssetContract = 14, 
    protocol_Transaction_Contract_ContractType_UpdateAssetContract = 15, 
    protocol_Transaction_Contract_ContractType_ProposalCreateContract = 16, 
    protocol_Transaction_Contract_ContractType_ProposalApproveContract = 17, 
    protocol_Transaction_Contract_ContractType_ProposalDeleteContract = 18, 
    protocol_Transaction_Contract_ContractType_SetAccountIdContract = 19, 
    protocol_Transaction_Contract_ContractType_CustomContract = 20, 
    protocol_Transaction_Contract_ContractType_CreateSmartContract = 30, 
    protocol_Transaction_Contract_ContractType_TriggerSmartContract = 31, 
    protocol_Transaction_Contract_ContractType_GetContract = 32, 
    protocol_Transaction_Contract_ContractType_UpdateSettingContract = 33, 
    protocol_Transaction_Contract_ContractType_ExchangeCreateContract = 41, 
    protocol_Transaction_Contract_ContractType_ExchangeInjectContract = 42, 
    protocol_Transaction_Contract_ContractType_ExchangeWithdrawContract = 43, 
    protocol_Transaction_Contract_ContractType_ExchangeTransactionContract = 44, 
    protocol_Transaction_Contract_ContractType_UpdateEnergyLimitContract = 45, 
    protocol_Transaction_Contract_ContractType_AccountPermissionUpdateContract = 46, 
    protocol_Transaction_Contract_ContractType_ClearABIContract = 48, 
    protocol_Transaction_Contract_ContractType_UpdateBrokerageContract = 49 
} protocol_Transaction_Contract_ContractType;

typedef enum _protocol_Transaction_Result_code { 
    protocol_Transaction_Result_code_SUCESS = 0, 
    protocol_Transaction_Result_code_FAILED = 1 
} protocol_Transaction_Result_code;

typedef enum _protocol_Transaction_Result_contractResult { 
    protocol_Transaction_Result_contractResult_DEFAULT = 0, 
    protocol_Transaction_Result_contractResult_SUCCESS = 1, 
    protocol_Transaction_Result_contractResult_REVERT = 2, 
    protocol_Transaction_Result_contractResult_BAD_JUMP_DESTINATION = 3, 
    protocol_Transaction_Result_contractResult_OUT_OF_MEMORY = 4, 
    protocol_Transaction_Result_contractResult_PRECOMPILED_CONTRACT = 5, 
    protocol_Transaction_Result_contractResult_STACK_TOO_SMALL = 6, 
    protocol_Transaction_Result_contractResult_STACK_TOO_LARGE = 7, 
    protocol_Transaction_Result_contractResult_ILLEGAL_OPERATION = 8, 
    protocol_Transaction_Result_contractResult_STACK_OVERFLOW = 9, 
    protocol_Transaction_Result_contractResult_OUT_OF_ENERGY = 10, 
    protocol_Transaction_Result_contractResult_OUT_OF_TIME = 11, 
    protocol_Transaction_Result_contractResult_JVM_STACK_OVER_FLOW = 12, 
    protocol_Transaction_Result_contractResult_UNKNOWN = 13, 
    protocol_Transaction_Result_contractResult_TRANSFER_FAILED = 14 
} protocol_Transaction_Result_contractResult;

typedef enum _protocol_Permission_PermissionType { 
    protocol_Permission_PermissionType_Owner = 0, 
    protocol_Permission_PermissionType_Witness = 1, 
    protocol_Permission_PermissionType_Active = 2 
} protocol_Permission_PermissionType;

/* Struct definitions */
/* AccountId, (name, address) use name, (null, address) use address, (name, null) use name, */
typedef struct _protocol_AccountId { 
    pb_callback_t name; 
    pb_callback_t address; 
} protocol_AccountId;

/* Exchange */
typedef struct _protocol_Exchange { 
    int64_t exchange_id; 
    pb_callback_t creator_address; 
    int64_t create_time; 
    pb_callback_t first_token_id; 
    int64_t first_token_balance; 
    pb_callback_t second_token_id; 
    int64_t second_token_balance; 
} protocol_Exchange;

typedef struct _protocol_Key { 
    pb_byte_t address[21]; 
    int64_t weight; 
} protocol_Key;

typedef struct _protocol_Transaction_Contract { 
    protocol_Transaction_Contract_ContractType type; 
    bool has_parameter;
    google_protobuf_Any parameter; 
    pb_callback_t provider; 
    pb_callback_t ContractName; 
    int32_t Permission_id; 
} protocol_Transaction_Contract;

typedef struct _protocol_Transaction_Result { 
    int64_t fee; 
    protocol_Transaction_Result_code ret; /* Owner id=0, Witness id=1, Active id start by 2 */
    protocol_Transaction_Result_contractResult contractRet; 
    pb_callback_t assetIssueID; 
    int64_t withdraw_amount; 
    int64_t unfreeze_amount; /* 1 bit 1 contract */
    int64_t exchange_received_amount; 
    int64_t exchange_inject_another_amount; 
    int64_t exchange_withdraw_another_amount; 
    int64_t exchange_id; 
} protocol_Transaction_Result;

typedef struct _protocol_authority { 
    bool has_account;
    protocol_AccountId account; 
    pb_callback_t permission_name; 
} protocol_authority;

typedef struct _protocol_Permission { 
    protocol_Permission_PermissionType type; 
    int32_t id; 
    pb_callback_t permission_name; 
    int64_t threshold; 
    int32_t parent_id; 
    pb_byte_t operations[32]; 
    pb_size_t keys_count;
    protocol_Key keys[3]; 
} protocol_Permission;

typedef struct _protocol_Transaction_raw { 
    pb_callback_t data; 
    pb_size_t contract_count;
    protocol_Transaction_Contract contract[1]; 
    int64_t fee_limit; 
} protocol_Transaction_raw;

typedef struct _protocol_Transaction { 
    bool has_raw_data;
    protocol_Transaction_raw raw_data; 
    /* only support size = 1,  repeated list here for muti-sig extension */
    pb_callback_t signature; 
    pb_callback_t ret; 
} protocol_Transaction;


/* Helper constants for enums */
#define _protocol_AccountType_MIN protocol_AccountType_Normal
#define _protocol_AccountType_MAX protocol_AccountType_Contract
#define _protocol_AccountType_ARRAYSIZE ((protocol_AccountType)(protocol_AccountType_Contract+1))

#define _protocol_Transaction_Contract_ContractType_MIN protocol_Transaction_Contract_ContractType_AccountCreateContract
#define _protocol_Transaction_Contract_ContractType_MAX protocol_Transaction_Contract_ContractType_UpdateBrokerageContract
#define _protocol_Transaction_Contract_ContractType_ARRAYSIZE ((protocol_Transaction_Contract_ContractType)(protocol_Transaction_Contract_ContractType_UpdateBrokerageContract+1))

#define _protocol_Transaction_Result_code_MIN protocol_Transaction_Result_code_SUCESS
#define _protocol_Transaction_Result_code_MAX protocol_Transaction_Result_code_FAILED
#define _protocol_Transaction_Result_code_ARRAYSIZE ((protocol_Transaction_Result_code)(protocol_Transaction_Result_code_FAILED+1))

#define _protocol_Transaction_Result_contractResult_MIN protocol_Transaction_Result_contractResult_DEFAULT
#define _protocol_Transaction_Result_contractResult_MAX protocol_Transaction_Result_contractResult_TRANSFER_FAILED
#define _protocol_Transaction_Result_contractResult_ARRAYSIZE ((protocol_Transaction_Result_contractResult)(protocol_Transaction_Result_contractResult_TRANSFER_FAILED+1))

#define _protocol_Permission_PermissionType_MIN protocol_Permission_PermissionType_Owner
#define _protocol_Permission_PermissionType_MAX protocol_Permission_PermissionType_Active
#define _protocol_Permission_PermissionType_ARRAYSIZE ((protocol_Permission_PermissionType)(protocol_Permission_PermissionType_Active+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protocol_Exchange_init_default           {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define protocol_AccountId_init_default          {{{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_authority_init_default          {false, protocol_AccountId_init_default, {{NULL}, NULL}}
#define protocol_Transaction_init_default        {false, protocol_Transaction_raw_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_Transaction_Contract_init_default {_protocol_Transaction_Contract_ContractType_MIN, false, google_protobuf_Any_init_default, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protocol_Transaction_Result_init_default {0, _protocol_Transaction_Result_code_MIN, _protocol_Transaction_Result_contractResult_MIN, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define protocol_Transaction_raw_init_default    {{{NULL}, NULL}, 0, {protocol_Transaction_Contract_init_default}, 0}
#define protocol_Key_init_default                {{0}, 0}
#define protocol_Permission_init_default         {_protocol_Permission_PermissionType_MIN, 0, {{NULL}, NULL}, 0, 0, {0}, 0, {protocol_Key_init_default, protocol_Key_init_default, protocol_Key_init_default}}
#define protocol_Exchange_init_zero              {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define protocol_AccountId_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_authority_init_zero             {false, protocol_AccountId_init_zero, {{NULL}, NULL}}
#define protocol_Transaction_init_zero           {false, protocol_Transaction_raw_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_Transaction_Contract_init_zero  {_protocol_Transaction_Contract_ContractType_MIN, false, google_protobuf_Any_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protocol_Transaction_Result_init_zero    {0, _protocol_Transaction_Result_code_MIN, _protocol_Transaction_Result_contractResult_MIN, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0}
#define protocol_Transaction_raw_init_zero       {{{NULL}, NULL}, 0, {protocol_Transaction_Contract_init_zero}, 0}
#define protocol_Key_init_zero                   {{0}, 0}
#define protocol_Permission_init_zero            {_protocol_Permission_PermissionType_MIN, 0, {{NULL}, NULL}, 0, 0, {0}, 0, {protocol_Key_init_zero, protocol_Key_init_zero, protocol_Key_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define protocol_AccountId_name_tag              1
#define protocol_AccountId_address_tag           2
#define protocol_Exchange_exchange_id_tag        1
#define protocol_Exchange_creator_address_tag    2
#define protocol_Exchange_create_time_tag        3
#define protocol_Exchange_first_token_id_tag     6
#define protocol_Exchange_first_token_balance_tag 7
#define protocol_Exchange_second_token_id_tag    8
#define protocol_Exchange_second_token_balance_tag 9
#define protocol_Key_address_tag                 1
#define protocol_Key_weight_tag                  2
#define protocol_Transaction_Contract_type_tag   1
#define protocol_Transaction_Contract_parameter_tag 2
#define protocol_Transaction_Contract_provider_tag 3
#define protocol_Transaction_Contract_ContractName_tag 4
#define protocol_Transaction_Contract_Permission_id_tag 5
#define protocol_Transaction_Result_fee_tag      1
#define protocol_Transaction_Result_ret_tag      2
#define protocol_Transaction_Result_contractRet_tag 3
#define protocol_Transaction_Result_assetIssueID_tag 14
#define protocol_Transaction_Result_withdraw_amount_tag 15
#define protocol_Transaction_Result_unfreeze_amount_tag 16
#define protocol_Transaction_Result_exchange_received_amount_tag 18
#define protocol_Transaction_Result_exchange_inject_another_amount_tag 19
#define protocol_Transaction_Result_exchange_withdraw_another_amount_tag 20
#define protocol_Transaction_Result_exchange_id_tag 21
#define protocol_authority_account_tag           1
#define protocol_authority_permission_name_tag   2
#define protocol_Permission_type_tag             1
#define protocol_Permission_id_tag               2
#define protocol_Permission_permission_name_tag  3
#define protocol_Permission_threshold_tag        4
#define protocol_Permission_parent_id_tag        5
#define protocol_Permission_operations_tag       6
#define protocol_Permission_keys_tag             7
#define protocol_Transaction_raw_data_tag        10
#define protocol_Transaction_raw_contract_tag    11
#define protocol_Transaction_raw_fee_limit_tag   18
#define protocol_Transaction_raw_data_tag        1
#define protocol_Transaction_signature_tag       2
#define protocol_Transaction_ret_tag             5

/* Struct field encoding specification for nanopb */
#define protocol_Exchange_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    exchange_id,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    creator_address,   2) \
X(a, STATIC,   SINGULAR, INT64,    create_time,       3) \
X(a, CALLBACK, SINGULAR, BYTES,    first_token_id,    6) \
X(a, STATIC,   SINGULAR, INT64,    first_token_balance,   7) \
X(a, CALLBACK, SINGULAR, BYTES,    second_token_id,   8) \
X(a, STATIC,   SINGULAR, INT64,    second_token_balance,   9)
#define protocol_Exchange_CALLBACK pb_default_field_callback
#define protocol_Exchange_DEFAULT NULL

#define protocol_AccountId_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    name,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    address,           2)
#define protocol_AccountId_CALLBACK pb_default_field_callback
#define protocol_AccountId_DEFAULT NULL

#define protocol_authority_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  account,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    permission_name,   2)
#define protocol_authority_CALLBACK pb_default_field_callback
#define protocol_authority_DEFAULT NULL
#define protocol_authority_account_MSGTYPE protocol_AccountId

#define protocol_Transaction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  raw_data,          1) \
X(a, CALLBACK, REPEATED, BYTES,    signature,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  ret,               5)
#define protocol_Transaction_CALLBACK pb_default_field_callback
#define protocol_Transaction_DEFAULT NULL
#define protocol_Transaction_raw_data_MSGTYPE protocol_Transaction_raw
#define protocol_Transaction_ret_MSGTYPE protocol_Transaction_Result

#define protocol_Transaction_Contract_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parameter,         2) \
X(a, CALLBACK, SINGULAR, BYTES,    provider,          3) \
X(a, CALLBACK, SINGULAR, BYTES,    ContractName,      4) \
X(a, STATIC,   SINGULAR, INT32,    Permission_id,     5)
#define protocol_Transaction_Contract_CALLBACK pb_default_field_callback
#define protocol_Transaction_Contract_DEFAULT NULL
#define protocol_Transaction_Contract_parameter_MSGTYPE google_protobuf_Any

#define protocol_Transaction_Result_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    fee,               1) \
X(a, STATIC,   SINGULAR, UENUM,    ret,               2) \
X(a, STATIC,   SINGULAR, UENUM,    contractRet,       3) \
X(a, CALLBACK, SINGULAR, STRING,   assetIssueID,     14) \
X(a, STATIC,   SINGULAR, INT64,    withdraw_amount,  15) \
X(a, STATIC,   SINGULAR, INT64,    unfreeze_amount,  16) \
X(a, STATIC,   SINGULAR, INT64,    exchange_received_amount,  18) \
X(a, STATIC,   SINGULAR, INT64,    exchange_inject_another_amount,  19) \
X(a, STATIC,   SINGULAR, INT64,    exchange_withdraw_another_amount,  20) \
X(a, STATIC,   SINGULAR, INT64,    exchange_id,      21)
#define protocol_Transaction_Result_CALLBACK pb_default_field_callback
#define protocol_Transaction_Result_DEFAULT NULL

#define protocol_Transaction_raw_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,             10) \
X(a, STATIC,   REPEATED, MESSAGE,  contract,         11) \
X(a, STATIC,   SINGULAR, INT64,    fee_limit,        18)
#define protocol_Transaction_raw_CALLBACK pb_default_field_callback
#define protocol_Transaction_raw_DEFAULT NULL
#define protocol_Transaction_raw_contract_MSGTYPE protocol_Transaction_Contract

#define protocol_Key_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, address,           1) \
X(a, STATIC,   SINGULAR, INT64,    weight,            2)
#define protocol_Key_CALLBACK NULL
#define protocol_Key_DEFAULT NULL

#define protocol_Permission_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, INT32,    id,                2) \
X(a, CALLBACK, SINGULAR, STRING,   permission_name,   3) \
X(a, STATIC,   SINGULAR, INT64,    threshold,         4) \
X(a, STATIC,   SINGULAR, INT32,    parent_id,         5) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, operations,        6) \
X(a, STATIC,   REPEATED, MESSAGE,  keys,              7)
#define protocol_Permission_CALLBACK pb_default_field_callback
#define protocol_Permission_DEFAULT NULL
#define protocol_Permission_keys_MSGTYPE protocol_Key

extern const pb_msgdesc_t protocol_Exchange_msg;
extern const pb_msgdesc_t protocol_AccountId_msg;
extern const pb_msgdesc_t protocol_authority_msg;
extern const pb_msgdesc_t protocol_Transaction_msg;
extern const pb_msgdesc_t protocol_Transaction_Contract_msg;
extern const pb_msgdesc_t protocol_Transaction_Result_msg;
extern const pb_msgdesc_t protocol_Transaction_raw_msg;
extern const pb_msgdesc_t protocol_Key_msg;
extern const pb_msgdesc_t protocol_Permission_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protocol_Exchange_fields &protocol_Exchange_msg
#define protocol_AccountId_fields &protocol_AccountId_msg
#define protocol_authority_fields &protocol_authority_msg
#define protocol_Transaction_fields &protocol_Transaction_msg
#define protocol_Transaction_Contract_fields &protocol_Transaction_Contract_msg
#define protocol_Transaction_Result_fields &protocol_Transaction_Result_msg
#define protocol_Transaction_raw_fields &protocol_Transaction_raw_msg
#define protocol_Key_fields &protocol_Key_msg
#define protocol_Permission_fields &protocol_Permission_msg

/* Maximum encoded size of messages (where known) */
/* protocol_Exchange_size depends on runtime parameters */
/* protocol_AccountId_size depends on runtime parameters */
/* protocol_authority_size depends on runtime parameters */
/* protocol_Transaction_size depends on runtime parameters */
/* protocol_Transaction_Contract_size depends on runtime parameters */
/* protocol_Transaction_Result_size depends on runtime parameters */
/* protocol_Transaction_raw_size depends on runtime parameters */
/* protocol_Permission_size depends on runtime parameters */
#define protocol_Key_size                        34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
