/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "core/Tron.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_Exchange, protocol_Exchange, AUTO)


PB_BIND(protocol_AccountId, protocol_AccountId, AUTO)


PB_BIND(protocol_authority, protocol_authority, AUTO)


PB_BIND(protocol_Transaction, protocol_Transaction, AUTO)


PB_BIND(protocol_Transaction_Contract, protocol_Transaction_Contract, AUTO)


PB_BIND(protocol_Transaction_Result, protocol_Transaction_Result, AUTO)


PB_BIND(protocol_Transaction_raw, protocol_Transaction_raw, AUTO)







